services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager

    restart: unless-stopped
    networks:
      - homelab

    ports:
    - "80:80"
    - "81:81"
    - "443:443"

    volumes:
    - npm-data:/data
    - npm-letsencrypt:/etc/letsencrypt

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:81 >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
 npm-data:
    external: true
 npm-letsencrypt:
    external: true

networks:
  homelab:
    external: true
   # name: homelab
