---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Plex:
        href: http://plex.home.arpa
        description: Movies & TV Shows
        widget:
          type: plex
          url: http://192.168.10.151:32400
          key: "{{HOMEPAGE_VAR_PLEX_TOKEN}}"

- Networking:
    - Adguard:
        href: http://adguard.home.arpa
        description: DNS Homepage
        widget:
          type: adguard
          url: http://192.168.10.151:8088
          username: "{{HOMEPAGE_VAR_SERVICE_USER}}"
          password: "{{HOMEPAGE_VAR_SERVICE_PASS}}"
    - NPM:
        href: http://npm.home.arpa
        description: Proxy manager


