services:
   plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    restart: unless-stopped
    security_opt:
     - label=disable
    
    
    environment:
      PUID: "1000"
      PGID: "1001"
      TZ: Africa/Johannesburg
      VERSION: docker
    
    
    volumes:
      - plex-config:/config
      - /srv/nas/media:/media:z
      - /tmp:/transcode
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
    
    
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS HTTP://127.0.0.1:32400/identity >/dev/null || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3


    
volumes:
  plex-config:
    external: true

